# Generated by Django 3.1 on 2020-08-22 14:07

import API.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=API.utils.get_input_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSegmentation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('input_image', models.FileField(blank=True, null=True, upload_to=API.utils.get_input_image_path)),
                ('output_image', models.FileField(blank=True, null=True, upload_to=API.utils.get_output_image_path)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
