# Generated by Django 3.1 on 2020-08-22 14:31

import API.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=API.utils.get_input_image_path),
        ),
    ]
